[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/backend.dockerfile"

[deploy]
startCommand = "npx ts-node src/server.ts"


[deploy.env]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=4096" 
