[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy]
startCommand = "npx prisma generate && npx prisma migrate deploy && npx ts-node src/server.ts "
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.env]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=4096"
